apiVersion: v1
kind: Pod
metadata:
  name: base
  namespace: aaas
spec:
  containers:
  - name: aaas-container
    image: atlasanalyticsservice/alarmandalertservice:latest
    args: ["sleep", "36500000"]
    env:
    - name: MAILGUN_API_KEY
      valueFrom:
        secretKeyRef:
          name: mailgun-secret
          key: api-key
    volumeMounts:
    - name: google-secret-vol
      mountPath: "/secrets"
      readOnly: true
    - name: config-volume
      mountPath: "/config"
      readOnly: true
  volumes:
  - name: google-secret-vol
    secret:
      secretName: google-secret  
  - name: config-volume
    secret:
      secretName: config
  restartPolicy: Always
