apiVersion: v1
kind: Pod
metadata:
  name: base
  namespace: aaas
spec:
  containers:
    - name: aaa-container
      image: sandci/alarms_and_alerts:latest
      args: ["sleep", "36500000"]
      # env:
      # - name: MAILGUN_API_KEY
      #   valueFrom:
      #     secretKeyRef:
      #       name: mailgun-secret
      #       key: api-key
      volumeMounts:
        - name: config-volume
          mountPath: "/config"
          readOnly: true
  volumes:
    - name: config-volume
      secret:
        secretName: config
  restartPolicy: Always
