apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ps-trace
  namespace: aaas
spec:
  schedule: "8 5 */15 * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: aaas-container
              image: sandci/alarms_and_alerts:latest
              imagePullPolicy: IfNotPresent
              command: ["/ps-trace.sh"]
              volumeMounts:
                - name: config-volume
                  mountPath: "/config"
                  readOnly: true
          volumes:
            - name: config-volume
              secret:
                secretName: config
          restartPolicy: Never
